apiVersion: v1
kind: Pod
metadata:
  name: reply-service-1
  namespace: ai-demo
  labels:
    app: reply-service
    instance: reply-service-1
spec:
  containers:
    - name: reply-service
      image: quay.io/kevent-mesh/ai-demo-reply-service:main
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: reply-service-2
  namespace: ai-demo
  labels:
    app: reply-service
    instance: reply-service-2
spec:
  containers:
    - name: reply-service
      image: quay.io/kevent-mesh/ai-demo-reply-service:main
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reply-service-internal-1
  namespace: ai-demo
spec:
  selector:
    instance: reply-service-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reply-service-internal-2
  namespace: ai-demo
spec:
  selector:
    instance: reply-service-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reply-service-exposed
  namespace: ai-demo
spec:
  selector:
    app: reply-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: reply-service
  namespace: ai-demo
spec:
  to:
    kind: Service
    name: reply-service-exposed
  port:
    targetPort: 8080
  wildcardPolicy: None
