apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/redhat-cop/gitops-catalog/serverless-operator/operator/overlays/stable?ref=main
  - github.com/redhat-cop/gitops-catalog/serverless-operator/instance/knative-serving/overlays/default?ref=main
  - github.com/redhat-cop/gitops-catalog/serverless-operator/instance/knative-eventing/base?ref=main
  - knative-kafka.yaml
  - minio-operator-namespace.yaml
  - minio-operator-operatorgroup.yaml
  - minio-operator-subscription.yaml
  - minio-storage-configuration.yaml
  - minio-tenant.yaml
  - minio-console-route.yaml
  - ai-demo-namespace.yaml
  - minio-webhook-source/event-display-service.yaml
  - minio-webhook-source/ksvc.yaml
  - minio-webhook-source/broker.yaml
  - upload-service/service.yaml
  - ui-service/configmap.yaml
  - ui-service/service.yaml
  - reply-service/service.yaml
  - reply-service/trigger.yaml
  - prediction-service/service.yaml
  - prediction-service/trigger.yaml
  - inference-service/service.yaml
  - analytics-service
  - feedback-service/ksvc.yaml
  - admin-service/ksvc.yaml

images:
- name: quay.io/kevent-mesh/ai-demo-inference-service-v1
  newName: "${DOCKER_REPO_OVERRIDE}/ai-demo-inference-service-v1"
  newTag: "${AI_DEMO_IMAGE_TAG}"
- name: quay.io/kevent-mesh/ai-demo-upload-service
  newName: "${DOCKER_REPO_OVERRIDE}/ai-demo-upload-service"
  newTag: "${AI_DEMO_IMAGE_TAG}"
- name: quay.io/kevent-mesh/ai-demo-minio-webhook-source
  newName: "${DOCKER_REPO_OVERRIDE}/ai-demo-minio-webhook-source"
  newTag: "${AI_DEMO_IMAGE_TAG}"
- name: quay.io/kevent-mesh/ai-demo-ui-service
  newName: "${DOCKER_REPO_OVERRIDE}/ai-demo-ui-service"
  newTag: "${AI_DEMO_IMAGE_TAG}"
- name: quay.io/kevent-mesh/ai-demo-reply-service
  newName: "${DOCKER_REPO_OVERRIDE}/ai-demo-reply-service"
  newTag: "${AI_DEMO_IMAGE_TAG}"
- name: quay.io/kevent-mesh/ai-demo-analytics-service
  newName: "${DOCKER_REPO_OVERRIDE}/ai-demo-analytics-service"
  newTag: "${AI_DEMO_IMAGE_TAG}"
- name: quay.io/kevent-mesh/ai-demo-prediction-service
  newName: "${DOCKER_REPO_OVERRIDE}/ai-demo-prediction-service"
  newTag: "${AI_DEMO_IMAGE_TAG}"
- name: quay.io/kevent-mesh/ai-demo-feedback-service
  newName: "${DOCKER_REPO_OVERRIDE}/ai-demo-feedback-service"
  newTag: "${AI_DEMO_IMAGE_TAG}"
- name: quay.io/kevent-mesh/ai-demo-admin-service
  newName: "${DOCKER_REPO_OVERRIDE}/ai-demo-admin-service"
  newTag: "${AI_DEMO_IMAGE_TAG}"
